//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_lab10.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\ChangeDatabase.mdf;Inte" +
            "grated Security=True;User Instance=True")]
        public string ChangeDatabaseConnectionString {
            get {
                return ((string)(this["ChangeDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-DRFH4VK;Initial Catalog=exchange_kurs;Integrated Security=Tru" +
            "e")]
        public string exchange_kursConnectionString {
            get {
                return ((string)(this["exchange_kursConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-DRFH4VK;Initial Catalog=\"C:\\DOCUMENTS AND SETTINGS\\MAX\\РАБОЧИ" +
            "Й СТОЛ\\КУРСОВЫЕ\\ОБМЕННЫЙ ПУНКТ\\ОБМЕННЫЙ ПУНКТ\\TP_KURS\\CHANGEDATABASE.MDF\";Integr" +
            "ated Security=True")]
        public string TP_KURS_CHANGEDATABASE_MDFConnectionString {
            get {
                return ((string)(this["TP_KURS_CHANGEDATABASE_MDFConnectionString"]));
            }
        }
    }
}
